/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20MinterBurner,
  IERC20MinterBurnerInterface,
} from "../../../contracts/BridgeComponents/IERC20MinterBurner";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20MinterBurner__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20MinterBurnerInterface {
    return new Interface(_abi) as IERC20MinterBurnerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): IERC20MinterBurner {
    return new Contract(address, _abi, runner) as unknown as IERC20MinterBurner;
  }
}
