/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMappingAdmin,
  IMappingAdminInterface,
} from "../../../contracts/BridgeComponents/IMappingAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_chainId",
        type: "uint16",
      },
      {
        internalType: "string",
        name: "_chainName",
        type: "string",
      },
    ],
    name: "addChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "_decimals",
        type: "uint8",
      },
    ],
    name: "mapNativeContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "_decimals",
        type: "uint8",
      },
    ],
    name: "mapWrappedContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_chainId",
        type: "uint16",
      },
      {
        internalType: "string",
        name: "_chainName",
        type: "string",
      },
    ],
    name: "updateChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMappingAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IMappingAdminInterface {
    return new Interface(_abi) as IMappingAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): IMappingAdmin {
    return new Contract(address, _abi, runner) as unknown as IMappingAdmin;
  }
}
