/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IChainLinkPriceFeeds,
  IChainLinkPriceFeedsInterface,
} from "../../../contracts/PriceOracle/IChainLinkPriceFeeds";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
    ],
    name: "getAssetPrice",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
    ],
    name: "getAssetPriceDecimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
    ],
    name: "getDataFeedAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IChainLinkPriceFeeds__factory {
  static readonly abi = _abi;
  static createInterface(): IChainLinkPriceFeedsInterface {
    return new Interface(_abi) as IChainLinkPriceFeedsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IChainLinkPriceFeeds {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IChainLinkPriceFeeds;
  }
}
