/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IChainLinkPriceFeedsAdmin,
  IChainLinkPriceFeedsAdminInterface,
} from "../../../contracts/PriceOracle/IChainLinkPriceFeedsAdmin";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "asset",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "dataFeed",
        type: "address",
      },
    ],
    name: "AssetDataFeedCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "asset",
        type: "string",
      },
    ],
    name: "AssetDataFeedDeleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "asset",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "dataFeed",
        type: "address",
      },
    ],
    name: "AssetDataFeedUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
      {
        internalType: "address",
        name: "dataFeed",
        type: "address",
      },
    ],
    name: "addDataFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
    ],
    name: "deleteDataFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
      {
        internalType: "address",
        name: "dataFeed",
        type: "address",
      },
    ],
    name: "updateDataFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IChainLinkPriceFeedsAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IChainLinkPriceFeedsAdminInterface {
    return new Interface(_abi) as IChainLinkPriceFeedsAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IChainLinkPriceFeedsAdmin {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IChainLinkPriceFeedsAdmin;
  }
}
