/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEmmetFeeOracleAdmin,
  IEmmetFeeOracleAdminInterface,
} from "../../../contracts/PriceOracle/IEmmetFeeOracleAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "chainName",
        type: "string",
      },
      {
        internalType: "uint64",
        name: "chainId_",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "domain_",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "txFee_",
        type: "uint64",
      },
      {
        internalType: "string",
        name: "nativeCoin_",
        type: "string",
      },
    ],
    name: "updateChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "coinName_",
        type: "string",
      },
      {
        components: [
          {
            internalType: "uint128",
            name: "minimum",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "percentage",
            type: "uint128",
          },
        ],
        internalType: "struct IEmmetFeeOracle.CoinFee",
        name: "coinFee_",
        type: "tuple",
      },
    ],
    name: "updateCoinFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "protocolFeeDivisor_",
        type: "uint256",
      },
    ],
    name: "updateProtocolFeeDivisor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEmmetFeeOracleAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IEmmetFeeOracleAdminInterface {
    return new Interface(_abi) as IEmmetFeeOracleAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEmmetFeeOracleAdmin {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IEmmetFeeOracleAdmin;
  }
}
